name: Generate snake

on:
  schedule:
    - cron: "0 0 * * *"
  workflow_dispatch:

permissions:
  contents: write

concurrency:
  group: snake
  cancel-in-progress: true

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Generate snake SVG
        uses: Platane/snk@v3
        with:
          github_user_name: DouglasiOSDeveloper
          outputs: |
            dist/snake.svg?palette=github-dark

      - name: Push snake to the output branch
        uses: crazy-max/ghaction-github-pages@v3
        with:
          target_branch: output
          build_dir: dist
          commit_message: "chore: update snake"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
